plugins {
    id "fabric-loom" version "1.9-SNAPSHOT"
    id "maven-publish"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    // JavaCV for FFmpeg encoding
    implementation "org.bytedeco:javacv-platform:${project.javacv_version}"
    implementation "org.bytedeco:ffmpeg:${project.ffmpeg_version}"
    implementation "org.bytedeco:ffmpeg:${project.ffmpeg_version}:windows-x86_64"
    implementation "org.bytedeco:ffmpeg:${project.ffmpeg_version}:linux-x86_64"
    implementation "org.bytedeco:ffmpeg:${project.ffmpeg_version}:macosx-x86_64"
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = Integer.parseInt(project.java_version)
}

java {
    sourceCompatibility = JavaVersion.toVersion(project.java_version)
    targetCompatibility = JavaVersion.toVersion(project.java_version)
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
    manifest {
        attributes([
            "Implementation-Title": project.archives_base_name,
            "Implementation-Version": project.version,
        ])
    }
}
