# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.1
loader_version=0.16.9

# Mod
mod_version=1.0.0
maven_group=com.replayrec
archives_base_name=replayrec

# Java
java_version=21

# Dependencies
fabric_version=0.111.0+1.21.4
javacv_version=1.5.11
ffmpeg_version=7.1-1.5.11
